### ISSUE TITLE
Explore if a native PDF viewer is possible

### ISSUE THREAD

**Issue by abi** [expo/harvard-cs50-app#6]

**Comment by abi** [comment]
Both of these modules require `react-native link`: https://github.com/wonday/react-native-pdf https://github.com/cnjon/react-native-pdf-view

`Webview`'s PDF viewer is good enough for now.

**Comment by xcarpentier** [comment]
Hi,

I’m working on a solution to have a PDF offline viewer (android capable, using expo):

https://github.com/xcarpentier/rn-pdf-reader-js
